version: '3'
services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=yourpassword123
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=temperature_predictions
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=your-super-secret-token

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=your-super-secret-token
      - INFLUXDB_ORG=myorg
      - INFLUXDB_BUCKET=temperature_predictions
    volumes:
      - ../DoModelTraining/models:/app/models

volumes:
  influxdb-data:
